package com.ars.srk.gateway;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-03-11T22:02:55.149+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.srk.org/GatewayService/", name = "GatewayPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GatewayPortType {

    @WebMethod(action = "http://www.srk.org/GatewayService/publishMessage")
    @Oneway
    public void publishMessage(
        @WebParam(partName = "parameters", name = "Message", targetNamespace = "http://www.srk.org/MuleMessageModel/")
        MessageType parameters
    );
}
