
package com.ars.srk.gateway;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-03-11T22:02:55.079+05:30
 * Generated source version: 2.5.1
 * 
 */
public final class GatewayPortType_GatewayBindingPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.srk.org/GatewayService/", "GatewayService");

    private GatewayPortType_GatewayBindingPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GatewayService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GatewayService ss = new GatewayService(wsdlURL, SERVICE_NAME);
        GatewayPortType port = ss.getGatewayBindingPort();  
        
        {
        System.out.println("Invoking publishMessage...");
        com.ars.srk.gateway.MessageType _publishMessage_parameters = null;
        port.publishMessage(_publishMessage_parameters);


        }

        System.exit(0);
    }

}
