package com.ars.srk.gateway;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-03-11T22:02:55.156+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "GatewayService", 
                  wsdlLocation = "file:/C:/Users/virajn/AnypointStudio/workspace/ChannelGatewayService/src/main/resources/wsdl/GatewayService.wsdl",
                  targetNamespace = "http://www.srk.org/GatewayService/") 
public class GatewayService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.srk.org/GatewayService/", "GatewayService");
    public final static QName GatewayBindingPort = new QName("http://www.srk.org/GatewayService/", "GatewayBindingPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/virajn/AnypointStudio/workspace/ChannelGatewayService/src/main/resources/wsdl/GatewayService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GatewayService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/virajn/AnypointStudio/workspace/ChannelGatewayService/src/main/resources/wsdl/GatewayService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GatewayService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GatewayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GatewayService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GatewayService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GatewayService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GatewayService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GatewayPortType
     */
    @WebEndpoint(name = "GatewayBindingPort")
    public GatewayPortType getGatewayBindingPort() {
        return super.getPort(GatewayBindingPort, GatewayPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GatewayPortType
     */
    @WebEndpoint(name = "GatewayBindingPort")
    public GatewayPortType getGatewayBindingPort(WebServiceFeature... features) {
        return super.getPort(GatewayBindingPort, GatewayPortType.class, features);
    }

}
