<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://www.srk.org/GatewayService/"
	xmlns:ivs="http://www.srk.org/GatewayService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:msg="http://www.srk.org/MuleMessageModel/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GatewayService"
	targetNamespace="http://www.srk.org/GatewayService/">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.srk.org/MuleMessageModel/"
				schemaLocation="../xsd/MuleMessageModel.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="Request">
		<wsdl:part element="msg:Message" name="parameters"/>
	</wsdl:message>		
	<wsdl:portType name="GatewayPortType">
		<wsdl:operation name="publishMessage">
			<wsdl:input message="ivs:Request"/>
		</wsdl:operation>		
	</wsdl:portType>
	<wsdl:binding name="GatewayBinding" type="ivs:GatewayPortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="publishMessage">
			<soap:operation
				soapAction="http://www.srk.org/GatewayService/publishMessage"/>
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>			
		</wsdl:operation>		
	</wsdl:binding>
	<wsdl:service name="GatewayService">
		<wsdl:port binding="ivs:GatewayBinding" name="GatewayBindingPort">
			<soap:address location="http://www.srk.org/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
